### ISSUE TITLE
Problème d'accès au token

### ISSUE THREAD

**Issue by cedsib** [LeClubber/iDiamant2Mqtt#2]
Depuis quelques jours et sans changer ma config, plus rien n'apparait dans mon MQTT et les logs de iDiamant2Mqtt renvoient cela en boucle :

```
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/usr/src/idiamant/server.py", line 10, in <module>
    iDiamant.getToken()
  File "/usr/src/idiamant/idiamant.py", line 32, in getToken
    print("Problème d'accès au token : attente de " + attente + " secondes")

```

J'ai vu que dans dev.netatmo, on pouvait générer un token dédié, c'est peut-être lié ?
Mais je ne sais pas où le mettre dans la config :
<img width="871" alt="Capture d’écran 2023-07-13 à 23 25 32" src="https://github.com/LeClubber/iDiamant2Mqtt/assets/55406881/0eb52a7a-9db5-4d3e-a842-14b1071876bd">

**Comment by Daniele70** [comment]
Si je ne me trompe, la methode d'autentification ici utilisée n'est plus supportée depuis fin 2022.
Elle a fonctionné jusqu'à il y a quelques semaines mais il semblerait qu'elle soit desormais fini.
J'ai pu faire refonctionner idiamant2mqtt en modifiant manuellement idiamant.py avec les token obtenus comme tu l'indiques ci-dessus mais la solution n'est evidemment pas perenne.
Malheuresuement je n'ai pas les competences pour aller plus loin

**Comment by cedsib** [comment]
Tu peux proposer le code tel que tu l'as modifié ? Pour que je l'applique aussi @Daniele70 ?

**Comment by Daniele70** [comment]
J'ai crée les access et refresh tokens dans Netatmo Connect, puis j'ai modifié le file idiamant.py pour les ecrire en dur.

J'utilise Docker; chez moi le fichier est dans :
/var/lib/docker/overlay2/7e119088713ad726385ccc1601cfdb5be43655dc748005e0ea0a253812f50977/diff/usr/src/idiamant
idiamant.py 

    def getToken():
	virer toutes les lignes entre :
        """ Récupération du token sepuis Netatmo """
	et :           
        jsonStatus = json.loads(response.text)
	puis modifier :
        iDiamant.access_token = "5xxxxxxxxxxxxx|8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        iDiamant.refresh_token = "5xxxxxxxxxxxxxxxxx|4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        iDiamant.expire_token = 10000
       le fichier devrait continuer avec :
       url = "https://api.netatmo.com/api/homesdata"
       ...

Cependant ca ne marche qu'un temps (si erreur ou refresh du token ca plante et je dois renouveller l'operation :-(
Je travaille encore mais je n'arrive pas à appliquer la procedure automatique indiquée en dans Netatmo.
Deja depuis le Step 1 - Redirect the user to Netatmo OAuth2 dialog, j'obtiens une erreur dans la mire d'autentification : "Array is not an allowed scope for App" donc je ne peux pas recuperer les token en automatique.
Je dois aussi verifier le refresh du token : pas sur que ca marche mais c'est long à tester car il faut attendre le timeout.
Je te tiens au courant ...

**Comment by Daniele70** [comment]
Ok, voici une solution un peu plus soignée meme si toujours plutot artisanale.
Je mets les instructions en franglais 

Create a dedicated folder for the new config file that will store and update the tokens
in this exemple : \Docker\iDiamant
Create a Config.txt file with just 3 lines :

5xxxxxxxxxxxxxxxxxxxxxxx|8yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
5xxxxxxxxxxxxxxxxxxxxxxx|4zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
10800

First and second line are Acces and Refresh Tokens from Netatmo Connect : under your app utilize "Token generator" with scopes read and write_bubendorff
Third line the refresh timing (any value : anyway it will be updated at program startup)

Create your idiamant2mqtt docker container as usual but adding the volume
-v /Docker/iDiamant:/hardconfig \
(to give the container access to the config file)

Stop your container

Update the py files in the container. In my case they are here :
/var/lib/docker/overlay2/7e119088713ad726385ccc1601cfdb5be43655dc748005e0ea0a253812f50977/diff/usr/src/idiamant

const.py

            #!/usr/bin/env python
            # -*- coding: utf-8 -*-
            # @Author: Jérémy BRAUD / DanyDADO
            
            import os
            from time import sleep
            
            class Constantes():
                
                # Recuperation des variables d'environnement
                mqttPort = int(os.getenv('MQTT_PORT', 1883))
                mqttHost = os.getenv('MQTT_HOST', "localhost")
                mqttTopic = os.getenv('MQTT_TOPIC', "homeassistant")
                mqttUser = os.getenv('MQTT_USER')
                mqttPassword = os.getenv('MQTT_PASSWORD')
                idiamantUser = os.getenv("IDIAMANT_USER")
                idiamantPassword = os.getenv("IDIAMANT_PASSWORD")
                idiamantClientId = os.getenv("IDIAMANT_CLIENT_ID")
                idiamantClientSecret = os.getenv("IDIAMANT_CLIENT_SECRET")
                ConfigFile = open(r"/hardconfig/Config.txt","r")
                ConfigFile.seek(0)
                AccToken = ConfigFile.readline().strip()
                RefToken = ConfigFile.readline().strip()
                ExpToken = int(ConfigFile.readline().strip())
                # reset token expiration timer to force a first refresh
                ExpToken = 10
                print("From Config file")
                print(AccToken)
                print(RefToken)
                print(ExpToken)
                ConfigFile.close()
                print("go")

idiamant.py

          #!/usr/bin/env python
          # -*- coding: utf-8 -*-
          # @Author: Jérémy BRAUD & DanyDADO
          
          import json
          import requests
          import paho.mqtt.client as mqtt
          from const import Constantes
          from time import sleep
          from datetime import datetime
          
          class iDiamant():
          
              access_token = ""
              refresh_token = ""
              expire_token = 10
              volets = {}
          
              @staticmethod
              def getToken():
                
                  iDiamant.access_token = Constantes.AccToken
                  iDiamant.refresh_token = Constantes.RefToken
                  iDiamant.expire_token = Constantes.ExpToken
          
                  url = "https://api.netatmo.com/api/homesdata"
                  headers = {"Authorization": "Bearer " + iDiamant.access_token}
                  response = requests.get(url, headers=headers)
                  jsonStatus = json.loads(response.text)
                  homes = jsonStatus['body']['homes']
                  for home in homes:
                      if 'modules' in home:
                          home_id = home['id']
                          modules = home['modules']
                          for module in modules:
                              if "NBR" == module['type']:
                                  iDiamant.volets[module['id']] = {
                                      'name':module['name'],
                                      'bridge':module['bridge'],
                                      'id_home':home_id
                                  }
          
              @staticmethod
              def updateToken():
                  """ Update d'un token en fin de vie """
                  print("Before Refresh")
                  print(iDiamant.access_token)
                  print(iDiamant.refresh_token)
                  print(iDiamant.expire_token)
                  url = "https://api.netatmo.com/oauth2/token"
                  data = {'grant_type': 'refresh_token', 
                      'refresh_token': iDiamant.refresh_token,
                      'client_id': Constantes.idiamantClientId,
                      'client_secret': Constantes.idiamantClientSecret
                  }
                  response = requests.post(url, data)
                  while 200 != response.status_code:
                      attente = 20
                      print("Problème d'accès au renouvellement de token : attente de 20 secondes")
                      sleep(attente)
                      response = requests.post(url, data)
                  jsonStatus = json.loads(response.text)
                  iDiamant.access_token = jsonStatus['access_token']
                  iDiamant.refresh_token = jsonStatus['refresh_token']
                  iDiamant.expire_token = int(jsonStatus['expires_in'])
                  ConfigFile = open(r"/hardconfig/Config.txt","w")
                  ConfigFile.seek(0)
                  ConfigFile.write(iDiamant.access_token + "\n")
                  ConfigFile.write(iDiamant.refresh_token + "\n")
                  ConfigFile.write(str(iDiamant.expire_token) + "\n")
                  ConfigFile.write("Latest Refresh : ")
                  ConfigFile.write(str(datetime.now()) + "\n")
                  ConfigFile.write("Only first 3 lines are usefull :\n")
                  ConfigFile.write("Line 1 : iDiamant.access_token\n")
                  ConfigFile.write("Line 2 : iDiamant.refresh_token\n")
                  ConfigFile.write("Line 3 : iDiamant.expire_token\n")
                  ConfigFile.write("The code will regularly update the tokens. If for any reason they should expire, please update them from Netatmo Connect\n")
                  ConfigFile.close()
                  print("After Refresh")
                  print(datetime.now())
                  print(iDiamant.access_token)
                  print(iDiamant.refresh_token)
                  print(iDiamant.expire_token)
          
              @staticmethod
              def publish(topic, playload, retain=True):
                  """ Publication des messages MQTT """
                  client = mqtt.Client()
                  if Constantes.mqttUser:
                      client.username_pw_set(Constantes.mqttUser, Constantes.mqttPassword)
                  client.connect(Constantes.mqttHost, Constantes.mqttPort, 60)
                  client.publish(topic, playload, retain=retain)
                  client.disconnect()
          
              @staticmethod
              def initDiscovery():
                  """ Publication des config pour discovery """
                  for volet in iDiamant.volets:
                      topic = Constantes.mqttTopic + "/cover/" + volet + "/config"
                      payload = '{'
                      payload += '"unique_id": "' + volet + '",'
                      payload += '"name": "' + iDiamant.volets[volet]['name'] + '",'
                      payload += '"command_topic": "' + Constantes.mqttTopic + '/cover/' + volet + '/set"'
                      payload += '}'
                      iDiamant.publish(topic, payload)


Start the Container and pray ...

**Comment by cedsib** [comment]
AND IT'S WORKING ! ! ! ! !

**Comment by cedsib** [comment]
if @LeClubber can add this code in the repo that would be amazing

**Comment by Daniele70** [comment]
Sorry, little update after longer testing.
Access token is renewed every 1.5h but it never change (at least after 2 days).
The new protocol states that Access Token should change at each renewal. It seems Netatmo is still partially applying the old protocol --> something like "Access token lifetime is extended by 3h at each renewal".
Anyway I updated the py files for more robustness in order to add a first renewal before the discovery of modules.
Code is not really '"lean" : I'm not a coding expert so there are some redundancies but it should work.
I tested relaunching the docker after 6 hours of shut down and it could start flawlessly (it was able to renew the Access token that finally changed).

The new files :

const.py

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    # @Author: Jérémy BRAUD / DanyDADO
    
    import os
    from time import sleep
    
    class Constantes():
        
        # Recuperation des variables d'environnement
        mqttPort = int(os.getenv('MQTT_PORT', 1883))
        mqttHost = os.getenv('MQTT_HOST', "localhost")
        mqttTopic = os.getenv('MQTT_TOPIC', "homeassistant")
        mqttUser = os.getenv('MQTT_USER')
        mqttPassword = os.getenv('MQTT_PASSWORD')
        idiamantUser = os.getenv("IDIAMANT_USER")
        idiamantPassword = os.getenv("IDIAMANT_PASSWORD")
        idiamantClientId = os.getenv("IDIAMANT_CLIENT_ID")
        idiamantClientSecret = os.getenv("IDIAMANT_CLIENT_SECRET")
        ConfigFile = open(r"/hardconfig/Config.txt","r")
        ConfigFile.seek(0)
        AccToken = ConfigFile.readline().strip()
        RefToken = ConfigFile.readline().strip()
        ExpToken = int(ConfigFile.readline().strip())
        # reset token expiration timer to force a first refresh or test update
        ExpToken = 10
        ConfigFile.close()
    

idiamant.py

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    # @Author: Jérémy BRAUD & DanyDADO
    
    import json
    import requests
    import paho.mqtt.client as mqtt
    from const import Constantes
    from time import sleep
    from datetime import datetime
    
    class iDiamant():
    
        access_token = ""
        refresh_token = ""
        expire_token = 10
        volets = {}
    
        @staticmethod
        def getToken():
          
            iDiamant.access_token = Constantes.AccToken
            iDiamant.refresh_token = Constantes.RefToken
            iDiamant.expire_token = Constantes.ExpToken
    
            """ first update of the token """
            print("Before First Refresh / From Config File")
            print(iDiamant.access_token)
            print(iDiamant.refresh_token)
            print(iDiamant.expire_token)
            url = "https://api.netatmo.com/oauth2/token"
            data = {'grant_type': 'refresh_token', 
                'refresh_token': iDiamant.refresh_token,
                'client_id': Constantes.idiamantClientId,
                'client_secret': Constantes.idiamantClientSecret
            }
            response = requests.post(url, data)
            while 200 != response.status_code:
                attente = 20
                print("Problème d'accès au renouvellement de token : attente de 20 secondes")
                sleep(attente)
                response = requests.post(url, data)
            jsonStatus = json.loads(response.text)
            iDiamant.access_token = jsonStatus['access_token']
            iDiamant.refresh_token = jsonStatus['refresh_token']
            iDiamant.expire_token = int(jsonStatus['expires_in'])
            ConfigFile = open(r"/hardconfig/Config.txt","w")
            ConfigFile.seek(0)
            ConfigFile.write(iDiamant.access_token + "\n")
            ConfigFile.write(iDiamant.refresh_token + "\n")
            ConfigFile.write(str(iDiamant.expire_token) + "\n")
            ConfigFile.write("Latest Refresh : ")
            ConfigFile.write(str(datetime.now()) + "\n")
            ConfigFile.write("Only first 3 lines are usefull :\n")
            ConfigFile.write("Line 1 : iDiamant.access_token\n")
            ConfigFile.write("Line 2 : iDiamant.refresh_token\n")
            ConfigFile.write("Line 3 : iDiamant.expire_token\n")
            ConfigFile.write("The code will regularly update the tokens. If for any reason they should expire, please update them from Netatmo Connect\n")
            ConfigFile.close()
            print("After First Refresh")
            print(datetime.now())
            print(iDiamant.access_token)
            print(iDiamant.refresh_token)
            print(iDiamant.expire_token)
    
            """ Reading modules """
            url = "https://api.netatmo.com/api/homesdata"
            headers = {"Authorization": "Bearer " + iDiamant.access_token}
            response = requests.get(url, headers=headers)
            jsonStatus = json.loads(response.text)
            homes = jsonStatus['body']['homes']
            for home in homes:
                if 'modules' in home:
                    home_id = home['id']
                    modules = home['modules']
                    for module in modules:
                        if "NBR" == module['type']:
                            iDiamant.volets[module['id']] = {
                                'name':module['name'],
                                'bridge':module['bridge'],
                                'id_home':home_id
                            }
    
        @staticmethod
        def updateToken():
            """ Update d'un token en fin de vie """
            print("Before Refresh")
            print(iDiamant.access_token)
            print(iDiamant.refresh_token)
            print(iDiamant.expire_token)
            url = "https://api.netatmo.com/oauth2/token"
            data = {'grant_type': 'refresh_token', 
                'refresh_token': iDiamant.refresh_token,
                'client_id': Constantes.idiamantClientId,
                'client_secret': Constantes.idiamantClientSecret
            }
            response = requests.post(url, data)
            while 200 != response.status_code:
                attente = 20
                print("Problème d'accès au renouvellement de token : attente de 20 secondes")
                sleep(attente)
                response = requests.post(url, data)
            jsonStatus = json.loads(response.text)
            iDiamant.access_token = jsonStatus['access_token']
            iDiamant.refresh_token = jsonStatus['refresh_token']
            iDiamant.expire_token = int(jsonStatus['expires_in'])
            ConfigFile = open(r"/hardconfig/Config.txt","w")
            ConfigFile.seek(0)
            ConfigFile.write(iDiamant.access_token + "\n")
            ConfigFile.write(iDiamant.refresh_token + "\n")
            ConfigFile.write(str(iDiamant.expire_token) + "\n")
            ConfigFile.write("Latest Refresh : ")
            ConfigFile.write(str(datetime.now()) + "\n")
            ConfigFile.write("Only first 3 lines are usefull :\n")
            ConfigFile.write("Line 1 : iDiamant.access_token\n")
            ConfigFile.write("Line 2 : iDiamant.refresh_token\n")
            ConfigFile.write("Line 3 : iDiamant.expire_token\n")
            ConfigFile.write("The code will regularly update the tokens. If for any reason they should expire, please update them from Netatmo Connect\n")
            ConfigFile.close()
            print("After Refresh")
            print(datetime.now())
            print(iDiamant.access_token)
            print(iDiamant.refresh_token)
            print(iDiamant.expire_token)
    
        @staticmethod
        def publish(topic, playload, retain=True):
            """ Publication des messages MQTT """
            client = mqtt.Client()
            if Constantes.mqttUser:
                client.username_pw_set(Constantes.mqttUser, Constantes.mqttPassword)
            client.connect(Constantes.mqttHost, Constantes.mqttPort, 60)
            client.publish(topic, playload, retain=retain)
            client.disconnect()
    
        @staticmethod
        def initDiscovery():
            """ Publication des config pour discovery """
            for volet in iDiamant.volets:
                topic = Constantes.mqttTopic + "/cover/" + volet + "/config"
                payload = '{'
                payload += '"unique_id": "' + volet + '",'
                payload += '"name": "' + iDiamant.volets[volet]['name'] + '",'
                payload += '"command_topic": "' + Constantes.mqttTopic + '/cover/' + volet + '/set"'
                payload += '}'
                iDiamant.publish(topic, payload)

**Comment by cedsib** [comment]
There is a quote to remove at the end but else it's working like a charm :-)

**Comment by LeClubber** [comment]
Le code est modifié pour prendre en compte les token généré.
J'ai préféré définir ce token en variable d'environnement à définir dans docker ou docker compose.

L'image docker a été mise à jour. Pour avoir la dernière version : docker pull leclubber/idiamant2mqtt

**Comment by cedsib** [comment]
ça marche comme un charme ! bravo !

**Comment by Daniele70** [comment]
Super !
J'avais mis un fichier externe de config pour que les tokens soient enregistrés en cas de mise à jour. Cependant la frequence de mise à jour ne corresponds pas aux indications de l'api. Donc à tester dans la durée.
Merci !
Bye
